### ISSUE TITLE
Error loading Crm365 Solution 

### ISSUE THREAD

**Issue by NikishinVlad** [rappen/CustomActionTester#23]
CRM 365 version 1612 (8.2.12.14)

Error

System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: 'Workflow' entity doesn't contain attribute with Name = 'iscustomprocessingstepallowedforotherpublishers'. (Дополнительные сведения об ошибке — Exception details: 

ErrorCode: 0x80041103

Message: 'Workflow' entity doesn't contain attribute with Name = 'iscustomprocessingstepallowedforotherpublishers'.

TimeStamp: 2021-08-02T09:39:34.2507771Z

--

Exception details: 

ErrorCode: 0x80041103

Message: 'Workflow' entity doesn't contain attribute with Name = 'iscustomprocessingstepallowedforotherpublishers'.

TimeStamp: 2021-08-02T09:39:34.2507771Z

**Comment by rappen** [comment]
Sorry, but I think it is not supported for version 8.2.
I'll be great if you have more info, or a MS Doc for it? 🙏

**Comment by rappen** [comment]
Fixed from @LycraLout - will be in new version.

**Comment by JadynWong** [comment]
Hi @rappen, thanks for the awesome tool. When will the new version of CustomActionTester be released?

**Comment by rappen** [comment]
Oh, I need to release next version... This week!
