### ISSUE TITLE
Contents of StringArray output parameters is not shown

### ISSUE THREAD

**Issue by filcole** [rappen/CustomActionTester#26]
Thank you for the very useful tool @rappen. I've found a small glitch in the CustomActionTester that I thought I'd share.

When a Custom API has an output parameter of type StringArray the output value displayed is always System.String[].  It would be good if it could display the contents of the string array.  This confused me (easily done) for a while until I checked in Dataverse REST Builder

![image](https://user-images.githubusercontent.com/6078398/192111362-2daa0074-74a1-4ce2-bfe5-6096ba41f938.png)

The string array is not an empty array, as seen in Dataverse REST Builder
![image](https://user-images.githubusercontent.com/6078398/192111440-bd2a0165-3652-428f-87dc-918ddb008e09.png)

**Comment by rappen** [comment]
This looks ok?

![image](https://user-images.githubusercontent.com/2572253/192815791-88f39061-bcb4-476c-ba84-a0f6dc142e68.png)

**Comment by rappen** [comment]
Coming "soon"... :)
